/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MemeRouteImport } from './routes/meme'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnIdRouteImport } from './routes/learn.$id'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsSymbolRouteImport } from './routes/markets.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeRoute = MemeRouteImport.update({
  id: '/meme',
  path: '/meme',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIdRoute = LearnIdRouteImport.update({
  id: '/learn/$id',
  path: '/learn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSymbolRoute = MarketsSymbolRouteImport.update({
  id: '/markets/$symbol',
  path: '/markets/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meme': typeof MemeRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/learn/$id': typeof LearnIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/learn/': typeof LearnIndexRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meme': typeof MemeRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/learn/$id': typeof LearnIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/learn': typeof LearnIndexRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/meme': typeof MemeRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/watchlist': typeof WatchlistRoute
  '/learn/$id': typeof LearnIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/learn/': typeof LearnIndexRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/meme'
    | '/portfolio'
    | '/trade'
    | '/watchlist'
    | '/learn/$id'
    | '/markets/$symbol'
    | '/learn/'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/meme'
    | '/portfolio'
    | '/trade'
    | '/watchlist'
    | '/learn/$id'
    | '/markets/$symbol'
    | '/learn'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/meme'
    | '/portfolio'
    | '/trade'
    | '/watchlist'
    | '/learn/$id'
    | '/markets/$symbol'
    | '/learn/'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MemeRoute: typeof MemeRoute
  PortfolioRoute: typeof PortfolioRoute
  TradeRoute: typeof TradeRoute
  WatchlistRoute: typeof WatchlistRoute
  LearnIdRoute: typeof LearnIdRoute
  MarketsSymbolRoute: typeof MarketsSymbolRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meme': {
      id: '/meme'
      path: '/meme'
      fullPath: '/meme'
      preLoaderRoute: typeof MemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$id': {
      id: '/learn/$id'
      path: '/learn/$id'
      fullPath: '/learn/$id'
      preLoaderRoute: typeof LearnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$symbol': {
      id: '/markets/$symbol'
      path: '/markets/$symbol'
      fullPath: '/markets/$symbol'
      preLoaderRoute: typeof MarketsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MemeRoute: MemeRoute,
  PortfolioRoute: PortfolioRoute,
  TradeRoute: TradeRoute,
  WatchlistRoute: WatchlistRoute,
  LearnIdRoute: LearnIdRoute,
  MarketsSymbolRoute: MarketsSymbolRoute,
  LearnIndexRoute: LearnIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
